<a href="https://colab.research.google.com/github/rsrijana/Journey-Journal/blob/master/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#selecting colums in from excel sheet
import pandas as pd
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'City': ['New York', 'Los Angeles', 'Chicago']
}
df = pd.DataFrame(data)
columns = df[['Name','Age']]
print(columns)

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35


In [ ]:
#Adding and Modifying Columns
import pandas as pd
data = {
    'A': [1, 2, 3],
    'B': [4, 5, 6]
}
df = pd.DataFrame(data)
df ['C'] = df['B']*2
print(df)

   A  B   C
0  1  4   8
1  2  5  10
2  3  6  12


In [ ]:
#Adding and Modifying Columns
import pandas as pd
import numpy as np
data = {
    'A': [1, 2, 3],
    'B': [4, 5, 6]
}
df = pd.DataFrame(data)
df['A'] = df['A'] + 3
print(df)

   A  B
0  4  4
1  5  5
2  6  6


In [ ]:
# Dealing with Missing Data
# Creating a sample DataFrame with NaN values
import pandas as pd
import numpy as np

data = {
    'A': [1, 2, np.nan, 4],
    'B': [5, np.nan, 7, 8],
    'C': [9, 10, 11, np.nan]
}
df = pd.DataFrame(data)
df_cleaned = df.dropna() # Drop rows with any missing values
print(df_cleaned)

     A    B    C
0  1.0  5.0  9.0


In [ ]:
# Fill missing values with a specific value
import pandas as pd
import numpy as np

data = {
    'A': [1, 2, np.nan, 4],
    'B': [5, np.nan, 7, 8],
    'C': [9, 10, 11, np.nan]
}
df = pd.DataFrame(data)
df_filled = df.fillna(2.5)
print(df_filled)

     A    B     C
0  1.0  5.0   9.0
1  2.0  2.5  10.0
2  2.5  7.0  11.0
3  4.0  8.0   2.5


In [ ]:
#Grouping and Aggregating Data
import pandas as pd
import numpy as np

data = {
    'A': [1, 2, np.nan, 4],
    'B': [5, np.nan, 7, 8],
    'C': [9, 10, 11, np.nan]
}

df = pd.DataFrame(data)
df['A'] = df['A'].fillna(df['A'].mean())
df['B'] = df['B'].fillna(df['B'].mean())
df['C'] = df['C'].fillna(df['C'].mean())
print(df)

          A         B     C
0  1.000000  5.000000   9.0
1  2.000000  6.666667  10.0
2  2.333333  7.000000  11.0
3  4.000000  8.000000  10.0


In [ ]:
#Grouping and Aggregating Data
import pandas as pd
import numpy as np

data = {
    'category': ['A', 'A', 'B', 'B', 'C', 'C'],
    'value1': [10, 15, 10, 20, 10, 30],
    'value2': [1, 2, 3, 4, 5, 6]
}
df = pd.DataFrame(data)
groupby = df.groupby('category').agg({'value1':'mean', 'value2':'sum'})
print(groupby)


          value1  value2
category                
A           12.5       3
B           15.0       7
C           20.0      11


In [ ]:
# Merging dataframes
import pandas as pd
import numpy as np

data1 = {
    'common_column': [1, 2, 3],
    'value1': ['A', 'B', 'C']
}
df1 = pd.DataFrame(data1)

data2 = {
    'common_column': [2, 3, 4],
    'value2': ['D', 'E', 'F']
}
df2 = pd.DataFrame(data2)
merge_df = pd.merge(df1,df2, on ='common_column' )
print(merge_df)

   common_column value1 value2
0              2      B      D
1              3      C      E


In [ ]:
# merging dataframes with joins
import pandas as pd
data1 = {
    'common_column': [1, 2, 3],
    'value1': ['A', 'B', 'C']
}
df1 = pd.DataFrame(data1)
data2 = {
    'common_column': [2, 3, 4],
    'value1': ['D', 'E', 'F']
}
df2 = pd.DataFrame(data2)
merge_data = pd.merge(df1, df2, on='common_column', how='right')
print(merge_data)

   common_column value1_x value1_y
0              2        B        D
1              3        C        E
2              4      NaN        F


In [ ]:
# Sorting
import pandas as pd
data = {
     'name': [ 'Charlie','Alice','David' ,'Bob'],
    'age': [25, 30, 35, 40],
    'score': [85, 92, 88, 90]
}
df = pd.DataFrame(data)
sort_data1 = df.sort_values(by=[ 'name','age'], ascending=[])
print(sort_data1)


      name  age  score
1    Alice   30     92
3      Bob   40     90
0  Charlie   25     85
2    David   35     88


In [2]:
# creating array
import numpy as np

array = np.array([1,2,3,4,5])
print(array)

[1 2 3 4 5]


In [9]:
import numpy as np
zeros = np.zeros(5)
print(zeros)
ones = np.ones(5)
print(ones)
range_array = np.arange(0, 10, 2)
print(range_array)

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[0 2 4 6 8]


In [14]:
import numpy as np

obj_array = np.array([1, 2, 3, 4, 5])
obj_array = array * 2
print(obj_array)

[ 4  6  8 10 12]
